### ISSUE TITLE
qml.MPS offset control

### ISSUE THREAD

**Issue by Daniil-Kuhmistrov** [PennyLaneAI/pennylane-sf#136]
I'm trying to figure out how qml.MPS (https://docs.pennylane.ai/en/stable/code/api/pennylane.MPS.html) works. The issue is there is no way to do arbitrary offset between blocks, it's automatically offsetting block by n_qubits_per_block/2. For example, having a block involving 8 wires, the next one will be 4 qubits lower. And I'm in situation when, for example, i want next block be 6 qubits lower. I couldn't find any parameters that is responsible for offset. However, It seems the authors of this article(https://arxiv.org/pdf/2209.11058.pdf) somehow managed to do that. Is it possible and if it is, how to control the offset.
Thanks in advance.

**Comment by isaacdevlugt** [comment]
Hey @Daniil-Kuhmistrov! I think this question is best suited for our forum: https://discuss.pennylane.ai. But, I'm happy to try and answer your question here 😄. 

I think I'm a little confused with how you want to use `qml.MPS`. Are you able to draw a small circuit that outlines how you would like `qml.MPS` to behave?

**Comment by isaacdevlugt** [comment]
We've moved the discussion to the forum!

https://discuss.pennylane.ai/t/qml-mps-offset-control/2890

Closing this issue.
