### ISSUE TITLE
Error when using `GaussianState` with `strawberryfields.fock` device

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/pennylane-sf#67]
#### Issue description

Trying to use `GaussianState` on the `strawberryfields.fock` device results in the error detailed below.

* *Expected behavior:* `GaussianState` should run without issues in a QNode.

* *Actual behavior:* An error is thrown, stemming from the Williamson decomposition in StrawberryFields.

* *Reproduces how often:* Always

#### System information

* **Operating system:**
  Ubuntu 20.04.2 LTS

* **PennyLane-SF version:**
0.16.0.dev

* **Python version:**
3.8.5

* **NumPy and SciPy versions:**
Numpy 1.18.5, Scipy 1.4.1

* **Installation method:**
Installed directly from master branch.

#### Source code and tracebacks

To reproduce:
```python
import pennylane as qml
import numpy as np

dev = qml.device('strawberryfields.fock', wires=2, cutoff_dim=10)

mean_vector = np.array([0, 0, 0, 0])
cov_mat = np.eye(4)

@qml.qnode(dev)
def quantum_neural_net():
    qml.GaussianState(mean_vector, cov_mat, wires=[0, 1])
    return qml.expval(qml.X(0))

quantum_neural_net()
```

The error log is:
```
------------------------------------
ValueErrorTraceback (most recent call last)
<ipython-input-4-d5155a8a9133> in <module>
----> 1 quantum_neural_net()

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/pennylane/qnode.py in __call__(self, *args, **kwargs)
    553 
    554         # execute the tape
--> 555         res = self.qtape.execute(device=self.device)
    556 
    557         if original_shots is not None:

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/pennylane/tape/tape.py in execute(self, device, params)
   1233             params = self.get_parameters()
   1234 
-> 1235         return self._execute(params, device=device)
   1236 
   1237     def execute_device(self, params, device):

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/autograd/tracer.py in f_wrapped(*args, **kwargs)
     46             return new_box(ans, trace, node)
     47         else:
---> 48             return f_raw(*args, **kwargs)
     49     f_wrapped.fun = f_raw
     50     f_wrapped._is_autograd_primitive = True

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/pennylane/interfaces/autograd.py in _execute(self, params, device)
    163         # evaluate the tape
    164         self.set_parameters(self._all_params_unwrapped, trainable_only=False)
--> 165         res = self.execute_device(params, device=device)
    166         self.set_parameters(self._all_parameter_values, trainable_only=False)
    167 

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/pennylane/tape/tape.py in execute_device(self, params, device)
   1266             res = device.execute(self)
   1267         else:
-> 1268             res = device.execute(self.operations, self.observables, {})
   1269 
   1270         # Update output dim if incorrect.

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/pennylane/_device.py in execute(self, queue, observables, parameters, **kwargs)
    409 
    410             for operation in queue:
--> 411                 self.apply(operation.name, operation.wires, operation.parameters)
    412 
    413             self.post_apply()

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/pennylane_sf/simulator.py in apply(self, operation, wires, par)
    109         par = [p.unwrap() if hasattr(p, "unwrap") else p for p in par]
    110 
--> 111         op = self._operation_map[operation](*sf_par)
    112         op | [self.q[i] for i in device_wires.labels]  # pylint: disable=pointless-statement
    113 

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/strawberryfields/ops.py in __init__(self, V, r, decomp, tol)
   2690 
   2691         # needed only if decomposed
-> 2692         th, self.S = dec.williamson(V, tol=tol)
   2693         self.pure = np.abs(np.linalg.det(V) - 1.0) < tol
   2694         self.nbar = 0.5 * (np.diag(th)[: self.ns] - 1.0)

~/Software/anaconda3/envs/xanadu/lib/python3.8/site-packages/strawberryfields/decompositions.py in williamson(V, tol)
    655             and ``S`` is a symplectic matrix such that :math:`V = S^T Db S`
    656     """
--> 657     (n, m) = V.shape
    658 
    659     if n != m:

ValueError: not enough values to unpack (expected 2, got 1)
```

#### Additional information

Running the exact same code on the `default.gaussian` device did not cause any errors.

**Comment by co9olguy** [comment]
It may be an error in SF itself, looking at the traceback. Or PennyLane is passing the wrong object to SF. Are you able to open a debugger and intercept what the object `V` is at line 2602 of `strawberryfields/ops.py`?

**Comment by co9olguy** [comment]
Also try reshaping `cov_mat` to be shape `(2,2,2,2)` instead of `(4,4)`

**Comment by LuyaoWang912** [comment]
The V at line 2692 means covariance matrix of gaussian state, which has shape 2N×2N.

**Comment by glassnotes** [comment]
> Also try reshaping cov_mat to be shape (2,2,2,2) instead of (4,4)

This didn't have any effect; am looking into the debugger.

**Comment by glassnotes** [comment]
I think there is a mismatch in the ordering of the variables. `V` in the debugger is showing up as the mean vector and not a matrix, which is what's passed to the WiIlliamson decomposition. In PennyLane, `GaussianState` takes mean vector `r` and matrix `V` in that order, but gets mapped to the SF operation `Gaussian`, which takes them in the order `V, r`.

**Comment by co9olguy** [comment]
Nice, thanks for the debugging expertise @glassnotes. 

Something that @thisac or @antalszava could very easily correct (and make a new test out of your example :wink:)

**Comment by LuyaoWang912** [comment]
> I think there is a mismatch in the ordering of the variables. `V` in the debugger is showing up as the mean vector and not a matrix, which is what's passed to the WiIlliamson decomposition. In PennyLane, `GaussianState` takes mean vector `r` and matrix `V` in that order, but gets mapped to the SF operation `Gaussian`, which takes them in the order `V, r`.
> 
> Edit: switching the order of the two when calling `GaussianState` indeed produces no errors.

That works. The order of V and r in GaussianState documentation is worry.
Thanks @glassnotes

**Comment by josh146** [comment]
Nice problem solving! Is the bug in the actual code, or is the bug in the docstring?

**Comment by glassnotes** [comment]
> Nice problem solving! Is the bug in the actual code, or is the bug in the docstring?

I think it's just in the docstring. The code works when you swap the arguments (the whole thing stems from a [user question](https://discuss.pennylane.ai/t/prepare-gaussianstate/993/5) and they confirmed the swap works) and the docstring in SF proper has them already in the correct order so I think it's just a matter of updating the one in PL.
