### ISSUE TITLE
PL qml.state() not supported on a simulator

### ISSUE THREAD

**Issue by sophchoe** [PennyLaneAI/pennylane-sf#75]
In the PL documentation, qml.state() is listed as one of the measurement options. However, when you run a code, it does not produce state vectors. Could you look into that? (Edit the documentation as an up and coming functionality). Otherwise, the flexibility of converting qnn as a Tensorflow or PyTorch layer is great! Thank you!

**Comment by CatalinaAlbornoz** [comment]
Hi @sophchoe, thank you for posting this here! We will take a look into it. Don't hesitate to let us know in case you want to give it a try to fix it.

**Comment by antalszava** [comment]
Hi @sophchoe, thank you again for reporting this! We've added notes to the PennyLane-SF docs.
